name: Metrics
on:
  # This workflow runs at 00:30 everyday
  schedule: [{cron: "30 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          plugin_stars: yes
          plugin_stars_limit: 4
          
          plugin_reactions: yes
          plugin_reactions_limit: 200                 # Compute reactions over last 200 issue comments
          plugin_reactions_days: 14                   # Compute reactions on issue comments posted less than 14 days ago
          plugin_reactions_details: count, percentage # Display reactions count and percentage
          plugin_reactions_ignored: bot
          
          plugin_stargazers: yes
          
          plugin_notable: yes
          plugin_notable_filter: stars:>200 # Only display repositories with 200 stars or more (syntax based on GitHub search query)
          plugin_notable_repositories: yes 
