name: Metrics
on:
  # This workflow runs at 00:30 everyday
  schedule: [{cron: "30 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          plugin_stars: yes
          plugin_stars_limit: 3

          # plugin_languages: yes
