# .github/workflows/mirror.yml
name: Mirror wtfismyip
on:
  schedule:
    - cron: "0 0 */10 * *"
  workflow_dispatch:
jobs:
  mirror1:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --bare https://gitlab.com/wtfismyip/wtfismyip.git .
      - run: git push --mirror "https://x:$GITHUB_TOKEN@github.com/Nsbx/wtfismyip-mirror.git"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
